import Foundation

enum WasteCategory: String, CaseIterable, Identifiable {
    case buildArtifacts = "Build artifacts"
    case developerCaches = "Developer caches"
    case appCaches = "App caches"
    case trash = "Trash"
    case installers = "Installers & archives"
    case staleDownloads = "Stale downloads"
    case logs = "Logs & crash reports"
    case bigAndOld = "Big & untouched"

    var id: String { rawValue }

    /// Rebuildable / regenerated automatically — safest to delete first.
    var isSafe: Bool {
        switch self {
        case .buildArtifacts, .developerCaches, .appCaches, .trash, .logs: return true
        case .installers, .staleDownloads, .bigAndOld: return false
        }
    }

    var blurb: String {
        switch self {
        case .buildArtifacts: return "Regenerated by your next build"
        case .developerCaches: return "Re-downloaded on demand by tooling"
        case .appCaches: return "Apps rebuild these automatically"
        case .trash: return "Already discarded, still on disk"
        case .installers: return "Disk images and archives you already installed"
        case .staleDownloads: return "Downloaded long ago, untouched since"
        case .logs: return "Diagnostics you are unlikely to read"
        case .bigAndOld: return "Large files you have not opened in a year"
        }
    }

    var symbol: String {
        switch self {
        case .buildArtifacts: return "hammer.fill"
        case .developerCaches: return "shippingbox.fill"
        case .appCaches: return "arrow.triangle.2.circlepath"
        case .trash: return "trash.fill"
        case .installers: return "opticaldisc.fill"
        case .staleDownloads: return "arrow.down.circle.fill"
        case .logs: return "doc.text.fill"
        case .bigAndOld: return "clock.badge.exclamationmark.fill"
        }
    }
}

struct WasteItem: Identifiable {
    let id = UUID()
    let node: FileItem
    let category: WasteCategory
    let reason: String
    var bytes: UInt64
    var path: String { node.path }
    var name: String { node.name }
}

enum WasteAnalyzer {
    private static let buildDirectories: Set<String> = [
        "node_modules", "DerivedData", "Pods", "__pycache__", ".next", ".nuxt",
        ".turbo", ".parcel-cache", "build", "target", ".gradle", ".dart_tool",
        "Carthage", ".terraform", ".mypy_cache", ".pytest_cache", ".ruff_cache",
    ]
    private static let developerCacheDirectories: Set<String> = [
        ".npm", ".yarn", ".pnpm-store", ".cargo", ".gradle", ".m2", ".cocoapods",
        ".rustup", ".nuget", ".pub-cache", ".bun", ".deno", ".electron",
        "iOS DeviceSupport", "watchOS DeviceSupport", "tvOS DeviceSupport",
    ]
    private static let installerExtensions: Set<String> = [
        "dmg", "pkg", "iso", "zip", "tar", "gz", "bz2", "xz", "7z", "rar", "msi", "exe",
    ]

    static let bigFileThreshold: UInt64 = 512 * 1024 * 1024
    static let staleInterval: TimeInterval = 90 * 86_400
    static let ancientInterval: TimeInterval = 365 * 86_400

    /// Walks the scanned tree once, collecting reclaimable nodes. A matched
    /// directory is reported whole; its contents are not examined further.
    static func analyze(root: FileItem, measure: SizeMeasure, now: Date = Date()) -> [WasteItem] {
        var found: [WasteItem] = []
        let home = FileManager.default.homeDirectoryForCurrentUser.path

        func visit(_ node: FileItem, path: String) {
            let size = node.size(measure)
            if size == 0 { return }

            if node.isDirectory {
                if let match = classifyDirectory(node, path: path, home: home) {
                    found.append(WasteItem(node: node, category: match.0,
                                           reason: match.1, bytes: size))
                    return  // Do not descend: the whole directory is the candidate.
                }
                for child in node.children {
                    visit(child, path: path + "/" + child.name)
                }
                return
            }

            if let match = classifyFile(node, path: path, home: home, size: size, now: now) {
                found.append(WasteItem(node: node, category: match.0,
                                       reason: match.1, bytes: size))
            }
        }

        // The root itself is never a candidate; start from its children.
        if root.isDirectory {
            for child in root.children {
                visit(child, path: root.path + "/" + child.name)
            }
        }
        return found.sorted { $0.bytes > $1.bytes }
    }

    private static func classifyDirectory(_ node: FileItem,
                                          path: String,
                                          home: String) -> (WasteCategory, String)? {
        let name = node.name

        if path == home + "/.Trash" || name == ".Trash" {
            return (.trash, "Trash contents")
        }
        if buildDirectories.contains(name) {
            // "build"/"target" only count next to a recognisable project marker.
            if name == "build" || name == "target" {
                guard let parent = node.parent, hasProjectMarker(parent) else { return nil }
            }
            return (.buildArtifacts, "\(name) — rebuildable output")
        }
        if developerCacheDirectories.contains(name) {
            return (.developerCaches, "\(name) — package/tooling cache")
        }
        if name == "Caches" || name == ".cache" {
            return (.appCaches, "Cache directory")
        }
        if name == "CoreSimulator", path.contains("/Library/Developer/") {
            return (.developerCaches, "Simulator runtimes and devices")
        }
        if name == "Logs", path.contains("/Library/") {
            return (.logs, "Log directory")
        }
        if name == "DiagnosticReports" {
            return (.logs, "Crash reports")
        }
        return nil
    }

    private static func hasProjectMarker(_ parent: FileItem) -> Bool {
        let markers: Set<String> = [
            "package.json", "Cargo.toml", "CMakeLists.txt", "Makefile",
            "pom.xml", "build.gradle", "build.gradle.kts", "meson.build",
        ]
        return parent.children.contains { markers.contains($0.name) }
    }

    private static func classifyFile(_ node: FileItem,
                                     path: String,
                                     home: String,
                                     size: UInt64,
                                     now: Date) -> (WasteCategory, String)? {
        let age = now.timeIntervalSince(node.modified)
        let ext = node.ext

        if ext == "log" && size > 10 * 1024 * 1024 {
            return (.logs, "Large log file")
        }
        if installerExtensions.contains(ext), size > 100 * 1024 * 1024, age > 30 * 86_400 {
            return (.installers, "\(ext.uppercased()) archive, \(days(age)) days old")
        }
        if path.hasPrefix(home + "/Downloads/"), age > staleInterval, size > 20 * 1024 * 1024 {
            return (.staleDownloads, "In Downloads, untouched for \(days(age)) days")
        }
        if size > bigFileThreshold, age > ancientInterval {
            return (.bigAndOld, "\(ByteFormat.string(size)), untouched for \(days(age)) days")
        }
        return nil
    }

    private static func days(_ interval: TimeInterval) -> Int {
        Int(interval / 86_400)
    }
}

struct WasteGroup: Identifiable {
    let category: WasteCategory
    var items: [WasteItem]
    var id: String { category.rawValue }
    var bytes: UInt64 { items.reduce(0) { $0 + $1.bytes } }
}

extension Array where Element == WasteItem {
    func grouped() -> [WasteGroup] {
        var buckets: [WasteCategory: [WasteItem]] = [:]
        for item in self { buckets[item.category, default: []].append(item) }
        return buckets
            .map { WasteGroup(category: $0.key, items: $0.value.sorted { $0.bytes > $1.bytes }) }
            .sorted { $0.bytes > $1.bytes }
    }
}
