#!/bin/bash
# Sets the version both apps ship as.
#
# VERSION is the source — the Mac app's build script already reads it — but
# Xcode cannot read a bare text file as a build setting, so the number is also
# written into an xcconfig the iOS target includes. One command writes both,
# which is what keeps them from drifting: the alternative was the same string
# typed into two files by hand, and the second one going stale.
set -euo pipefail
cd "$(dirname "$0")/.."

VERSION="${1:-$(cat VERSION)}"
if ! [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "usage: $0 <major.minor.patch>" >&2
  exit 1
fi

printf '%s\n' "$VERSION" > VERSION

# Committed rather than ignored, like the generated icon: a fresh clone should
# build something correctly versioned without having to run this first.
cat > iOS/Version.xcconfig <<CONFIG
// Generated by Scripts/set_version.sh — do not edit by hand.
// The version lives in VERSION at the root, which the Mac app reads directly.
MARKETING_VERSION = $VERSION
CONFIG

echo "version $VERSION — VERSION, iOS/Version.xcconfig"
